---
- name: Configure Cluster Manager
  hosts: manager0
  become: true
  remote_user: ubuntu
  
  tasks:

  - name: Update all packages to their latest version
    ansible.builtin.apt:
      name: "*"
      state: latest
      lock_timeout: 30

  - name: Configure indexer clustering
    command: "/opt/splunk/bin/splunk edit cluster-config -mode manager -replication_factor 2 -search_factor 2 -secret idxcluster1 -cluster_label idxcluster1 -auth admin:Administrator1!"

  - name: Restart Splunk
    command: "/opt/splunk/bin/splunk restart"