---
- name: Configure Cluster Manager
  hosts: manager0
  vars:
    license_manager: "splunkmgr1"
    deployment_server: "splunkmgr1"
    cluster_manager: "splunkmgr0"
    deployer: "splunkmgr1"
    sh_captain: "splunksh0"
  become: true
  remote_user: splunk
  gather_facts: false
  
  tasks:

# General tasks

  - name: Make sure splunk folder is owned by splunk user
    file:
      path: /opt/splunk
      owner: splunk
      recurse: yes

  - name: Populate service facts
    service_facts:

  - name: Check if Splunkd is running
    systemd_service:
      name: Splunkd.service
      state: started
    check_mode: true
    when: ansible_facts['services']['Splunkd.service']['status'] | default('not-found') != 'not-found'
    register: splunkd

  - name: Initialise and set boot start
    command: "/opt/splunk/bin/splunk enable boot-start -systemd-managed 1 -user splunk --accept-license --answer-yes --seed-passwd Administrator1!"
    when: splunkd.changed == "true" or ansible_facts['services']['Splunkd.service']['status'] | default('not-found') == 'not-found'

  - name: Set HTTPS
    command: "/opt/splunk/bin/splunk enable web-ssl -auth admin:Administrator1!"
    ignore_errors: true
  
  - name: Add license Manager
    command: "/opt/splunk/bin/splunk edit licenser-localpeer -manager_uri 'https://{{ license_manager }}.aws.maximumpigs.com:8089'"
    when: license_manager != inventory_hostname_short

  - name: Create Index and Forward App
    blockinfile: 
      path: /opt/splunk/etc/apps/index_and_forward/default/outputs.conf
      create: true
      mode: '0655'
      owner: 'splunk'
      prepend_newline: true
      block: |
        [indexAndForward]
        index = false

        [tcpout]
        defaultGroup = discovery-group
        indexAndForward = false

        [tcpout:discovery-group]
        indexerDiscovery = idxdiscovery1

        [indexer_discovery:idxdiscovery1]
        manager_uri=https://splunkmgr0.aws.maximumpigs.com:8089
        pass4SymmKey = idxdiscovery1

# Node specific tasks

  - name: Configure indexer clustering
    command: "/opt/splunk/bin/splunk edit cluster-config -mode manager -replication_factor 2 -search_factor 2 -secret idxcluster1 -cluster_label idxcluster1" 

## Configure Indexer Discovery

  - name: Create server.conf in cm_idx_discovery_base/default
    blockinfile: 
      path: /opt/splunk/etc/apps/cm_idx_discovery_base/default/server.conf
      create: true
      mode: '0655'
      owner: 'splunk'
      prepend_newline: true
      block: |
        [indexer_discovery]
        pass4SymmKey = idxdiscovery1

## Add inputs app - listen on 9997

  - name: Create inputs.conf in idx_inputs_base/default
    blockinfile: 
      path: /opt/splunk/etc/manager-apps/idx_inputs_base/default/inputs.conf
      create: true
      mode: '0655'
      owner: 'splunk'
      prepend_newline: true
      block: |
        [splunktcp://9997]
        disabled = 0

  - name: Start Splunk
    systemd_service:
      name: Splunkd.service
      state: started
    when: splunkd.changed == "true" or ansible_facts['services']['Splunkd.service']['status'] | default('not-found') == 'not-found'

  - name: Restart Splunk
    systemd_service:
      name: Splunkd.service
      state: restarted
    when: splunkd.changed == "false"