---
- name: Configure Cluster Manager
  hosts: manager0
  vars:
    license_manager: "splunkmgr1"
    deployment_server: "splunkmgr1"
    cluster_manager: "splunkmgr0"
    deployer: "splunkmgr1"
    sh_captain: "splunksh0"
  become: true
  remote_user: splunk
  
  tasks:

  - name: Set HTTPS
    command: "/opt/splunk/bin/splunk enable web-ssl -auth admin:Administrator1!"

  - name: Add license Manager
    command: "/opt/splunk/bin/splunk edit licenser-localpeer -manager_uri 'https://{{ license_manager }}.aws.maximumpigs.com:8089'"
    when: license_manager != inventory_hostname_short

  - name: Set Deployment Server
    command: "/opt/splunk/bin/splunk set deploy-poll https://{{ deployment_server }}.aws.maximumpigs.com:8089"
    when: deployment_server != inventory_hostname_short

  - name: Extract index_and_forward app
    unarchive:
      remote_src: yes
      src: /opt/index_and_forward.tgz
      dest: /opt/splunk/etc/apps/    

  - name: Configure indexer clustering
    command: "/opt/splunk/bin/splunk edit cluster-config -mode manager -replication_factor 2 -search_factor 2 -secret idxcluster1 -cluster_label idxcluster1" 

## Configure Indexer Discovery

  - name: Create server.conf in cm_idx_discovery_base/default
    blockinfile: 
      path: /opt/splunk/etc/apps/cm_idx_discovery_base/default/server.conf
      create: true
      mode: '0655'
      owner: 'splunk'
      prepend_newline: true
      block: |
        [indexer_discovery]
        pass4SymmKey = idxdiscovery1

## Add inputs app - listen on 9997

  - name: Create inputs.conf in idx_inputs_base/default
    blockinfile: 
      path: /opt/splunk/etc/manager-apps/idx_inputs_base/default/inputs.conf
      create: true
      mode: '0655'
      owner: 'splunk'
      prepend_newline: true
      block: |
        [splunktcp://9997]
        disabled = 0

  - name: Restart Splunk
    command: "/opt/splunk/bin/splunk restart"