---
- name: Configure Cluster Manager
  hosts: manager0
  become: true
  remote_user: ubuntu
  
  tasks:

  - name: Set HTTPS
    command: "/opt/splunk/bin/splunk enable web-ssl -auth admin:Administrator1!"

  - name: Add license Manager
    command: "/opt/splunk/bin/splunk edit licenser-localpeer -manager_uri https://splunkmgr1.aws.maximumpigs.com:8089 -auth admin:Administrator1!"

  - name: Set Deployment Server
    command: "/opt/splunk/bin/splunk set deploy-poll https://splunkmgr1.aws.maximumpigs.com:8089 -auth admin:Administrator1!"

# TODO - Reconsider doing this in serverclass.conf on the deployment server. - See if it's possible to add this host to 2 different server classes, one to receive cluster apps and the other to recieve base apps

  # - name: Check for [deployment-client] stanza
  #   lineinfile:
  #     name: /opt/splunk/etc/system/local/deploymentclient.conf
  #     search_string: '[deployment-client]'
  #     line: '[deployment-client]'
  #     state: present

  # - name: Remove repositoryLocation from deploymentclient.conf
  #   lineinfile:
  #     name: /opt/splunk/etc/system/local/deploymentclient.conf
  #     regexp: '^repositoryLocation'
  #     state: absent

  # - name: Remove repositoryLocation from deploymentclient.conf
  #   lineinfile:
  #     name: /opt/splunk/etc/system/local/deploymentclient.conf
  #     regexp: '^serverRepositoryLocationPolicy'
  #     state: absent      

  # - name: Add new repositoryLocation
  #   lineinfile:
  #     path: /opt/splunk/etc/system/local/deploymentclient.conf
  #     line: 'repositoryLocation = $SPLUNK_HOME/etc/manager-apps'
  #     insertafter: '^\[deployment-client\]'
  #     state: present

  # - name: Add new serverRepositoryLocationPolicy
  #   lineinfile:
  #     path: /opt/splunk/etc/system/local/deploymentclient.conf
  #     line: 'serverRepositoryLocationPolicy = rejectAlways'
  #     insertafter: '^\[deployment-client\]'
  #     state: present

  - name: Configure indexer clustering
    command: "/opt/splunk/bin/splunk edit cluster-config -mode manager -replication_factor 2 -search_factor 2 -secret idxcluster1 -cluster_label idxcluster1 -auth admin:Administrator1!"

  - name: Restart Splunk
    command: "/opt/splunk/bin/splunk restart"