---
- name: Configure Cluster Manager
  hosts: manager0
  become: true
  remote_user: ubuntu
  
  tasks:

  # - name: Add license Manager
  #   command: "/opt/splunk/bin/splunk edit licenser-localpeer -manager_uri https://splunkmgr1.aws.maximumpigs.com:8089 -auth admin:Administrator1!"

  - name: Set Deployment Server
    command: "/opt/splunk/bin/splunk set deploy-poll https://splunkmgr1.aws.maximumpigs.com:8089 -auth admin:Administrator1!"

## TODO - Modify deployment server with repositoryLocation = SPLUNK_HOME/etc/manager-apps and serverRepositoryLocationPolicy = rejectAlways

  - name: Configure indexer clustering
    command: "/opt/splunk/bin/splunk edit cluster-config -mode manager -replication_factor 2 -search_factor 2 -secret idxcluster1 -cluster_label idxcluster1 -auth admin:Administrator1!"

  - name: Restart Splunk
    command: "/opt/splunk/bin/splunk restart"