---
- name: Configure Deployer
  hosts: manager0
  become: true
  remote_user: ubuntu

  tasks:

  - name: Configure the deployer for SH Clustering
    command: "/opt/splunk/bin/splunk edit shcluster-config -secret shcluster1 -shcluster_label shcluster1 -auth admin:Administrator1!"

  - name: Restart Splunk
    command: "/opt/splunk/bin/splunk restart"