---
- name: Configure Deployment Server
  hosts: manager1
  vars:
    license_manager: "splunkmgr1"
    deployment_server: "splunkmgr1"
    cluster_manager: "splunkmgr0"
    deployer: "splunkmgr1"
    sh_captain: "splunksh0"
  become: true
  remote_user: splunk

  tasks:

  - name: Set HTTPS
    command: "/opt/splunk/bin/splunk enable web-ssl -auth admin:Administrator1!"
  
  - name: Add license Manager
    command: "/opt/splunk/bin/splunk edit licenser-localpeer -manager_uri 'https://{{ license_manager }}.aws.maximumpigs.com:8089'"
    when: license_manager != inventory_hostname_short

  - name: Extract index_and_forward app
    unarchive:
      remote_src: yes
      src: /opt/index_and_forward.tgz
      dest: /opt/splunk/etc/apps/

  - name: Extract index_and_forward app to deployment-apps
    unarchive:
      remote_src: yes
      src: /opt/index_and_forward.tgz
      dest: /opt/splunk/etc/deployment-apps/      

# TODO Set Deployment Server Classes

  - name: Start Splunk
    command: "/opt/splunk/bin/splunk start"