---
- name: Configure Indexer
  hosts: indexer
  become: true
  become_user: "splunk"
  remote_user: ubuntu
  
  tasks:

  - name: Update all packages to their latest version
    ansible.builtin.apt:
      name: "*"
      state: latest
      lock_timeout: 30

  - name: Join the indexer cluster
    command: "/opt/splunk/bin/splunk edit cluster-config -mode peer -manager_uri https://splunkmgr0.aws.maximumpigs.com:8089 -replication_port 9887 -secret idxcluster1 -auth admin:Administrator1!"

  - name: Restart Splunk
    command: "/opt/splunk/bin/splunk restart"