---
- name: Configure Indexer
  hosts: indexer
  vars:
    license_manager: "splunkmgr1"
    deployment_server: "splunkmgr1"
    cluster_manager: "splunkmgr0"
    deployer: "splunkmgr1"
    sh_captain: "splunksh0"
  become: true
  remote_user: splunk
  
  tasks:

# General tasks

  - name: Make sure splunk folder is owned by splunk user
    file:
      path: /opt/splunk
      owner: splunk
      recurse: yes

  - name: Populate service facts
    service_facts:

  - name: Check if Splunkd is running
    systemd_service:
      name: Splunkd.service
      state: started
    check_mode: true
    when: ansible_facts['services']['Splunkd.service']['status'] | default('not-found') != 'not-found'
    register: splunkd

  - name: Initialise and set boot start
    command: "/opt/splunk/bin/splunk enable boot-start -systemd-managed 1 -user splunk --accept-license --answer-yes --seed-passwd Administrator1!"
    when: ansible_facts['services']['Splunkd.service']['status'] | default('not-found') == 'not-found'

  - name: Add license Manager
    command: "/opt/splunk/bin/splunk edit licenser-localpeer -manager_uri 'https://{{ license_manager }}.aws.maximumpigs.com:8089'"
    when: license_manager != inventory_hostname_short

  - name: Create Index and Forward App
    blockinfile: 
      path: /opt/splunk/etc/apps/index_and_forward/default/outputs.conf
      create: true
      mode: '0655'
      owner: 'splunk'
      prepend_newline: true
      block: |
        [indexAndForward]
        index = false

        [tcpout]
        defaultGroup = discovery-group
        indexAndForward = false

        [tcpout:discovery-group]
        indexerDiscovery = idxdiscovery1

        [indexer_discovery:idxdiscovery1]
        manager_uri=https://splunkmgr0.aws.maximumpigs.com:8089
        pass4SymmKey = idxdiscovery1

  - name: Join the indexer cluster
    command: "/opt/splunk/bin/splunk edit cluster-config -mode peer -manager_uri https://{{ cluster_manager }}.aws.maximumpigs.com:8089 -replication_port 9887 -cluster_label idxcluster1 -secret idxcluster1"

  - name: Start Splunk
    systemd_service:
      name: Splunkd.service
      state: started
    when: '"splunkd is not running" in splunkd.stdout' 

  - name: Restart Splunk
    systemd_service:
      name: Splunkd.service
      state: restarted
    when: '"splunkd is running" in splunkd.stdout'

  - name: Add license Manager
    command: "/opt/splunk/bin/splunk edit licenser-localpeer -manager_uri 'https://{{ license_manager }}.aws.maximumpigs.com:8089'"
    when: license_manager != inventory_hostname_short    