---
- name: Configure Cluster Manager
  hosts: manager1
  become: true
  remote_user: ubuntu
  
  tasks:

  - name: Set HTTPS
    command: "/opt/splunk/bin/splunk enable web-ssl -auth admin:Administrator1!"

# TODO - test

  - name: Add license
    command: "/opt/splunk/bin/splunk add licenses /opt/splunk.license -auth admin:Administrator1!"

  - name: Restart Splunk
    command: "/opt/splunk/bin/splunk restart"