---
- name: Configure License Manager
  hosts: manager1
  vars:
    license_manager: "splunkmgr1"
    deployment_server: "splunkmgr1"
    cluster_manager: "splunkmgr0"
    deployer: "splunkmgr1"
    sh_captain: "splunksh0"
  become: true
  remote_user: splunk
  
  tasks:

  - name: Set HTTPS
    command: "/opt/splunk/bin/splunk enable web-ssl -auth admin:Administrator1!"

  - name: Check for existing license
    lineinfile:
      path: /opt/splunk/etc/system/local/server.conf
      line: '[license]'
      state: present
    check_mode: yes
    ignore_errors: yes
    register: license

  - name: Add license
    command: "/opt/splunk/bin/splunk add licenses /opt/splunk.license -auth admin:Administrator1!"
    when: license.changed == false

  - name: Set Deployment Server
    command: "/opt/splunk/bin/splunk set deploy-poll https://{{ deployment_server }}.aws.maximumpigs.com:8089 -auth admin:Administrator1!"
    when: deployment_server != inventory_hostname_short

  - name: Extract index_and_forward app
    unarchive:
      remote_src: yes
      src: /opt/index_and_forward.tgz
      dest: /opt/splunk/etc/apps/

  - name: Restart Splunk
    command: "/opt/splunk/bin/splunk restart"