---
- name: Configure License Manager
  hosts: manager1
  vars:
    license_manager: "splunkmgr1"
    deployment_server: "splunkmgr1"
    cluster_manager: "splunkmgr0"
    deployer: "splunkmgr1"
    sh_captain: "splunksh0"
  become: true
  remote_user: ubuntu
  
  tasks:

  - name: Set HTTPS
    command: "/opt/splunk/bin/splunk enable web-ssl -auth admin:Administrator1!"

  - name: Add license
    command: "/opt/splunk/bin/splunk add licenses /opt/splunk.license -auth admin:Administrator1!"

  - name: Set Deployment Server
    command: "/opt/splunk/bin/splunk set deploy-poll https://{{ deployment_server }}.aws.maximumpigs.com:8089 -auth admin:Administrator1!"
    when: deployment_server != inventory_hostname_short    

  - name: Restart Splunk
    command: "/opt/splunk/bin/splunk restart"