---
- name: Configure common configuration items
  hosts: manager1
  vars:
    license_manager: "splunkmgr1"
    deployment_server: "splunkmgr1"
    cluster_manager: "splunkmgr0"
    deployer: "splunkmgr1"
    sh_captain: "splunksh0"
  become: true
  remote_user: splunk
  
  tasks:

  - name: Initialise and set boot start
    command: "/opt/splunk/bin/splunk enable boot-start -systemd-managed 1 -user splunk --accept-license --answer-yes --seed-passwd Administrator1!"

  - name: Set HTTPS
    command: "/opt/splunk/bin/splunk enable web-ssl -auth admin:Administrator1!"

  - name: Add license Manager
    command: "/opt/splunk/bin/splunk edit licenser-localpeer -manager_uri 'https://{{ license_manager }}.aws.maximumpigs.com:8089'"
    when: license_manager != inventory_hostname_short

  - name: Set Deployment Server
    command: "/opt/splunk/bin/splunk set deploy-poll https://{{ deployment_server }}.aws.maximumpigs.com:8089"
    when: deployment_server != inventory_hostname_short    

## Configure Forwarding

  - name: Create Index and Forward App
    blockinfile: 
      path: /opt/splunk/etc/apps/index_and_forward/default/outputs.conf
      create: true
      mode: '0655'
      owner: 'splunk'
      prepend_newline: true
      block: |
        [indexAndForward]
        index = false

        [tcpout]
        defaultGroup = discovery-group
        indexAndForward = false

        [tcpout:discovery-group]
        indexerDiscovery = idxdiscovery1

        [indexer_discovery:idxdiscovery1]
        manager_uri=https://splunkmgr0.aws.maximumpigs.com:8089
        pass4SymmKey = idxdiscovery1  

  - name: Add as a searchead to indexer cluster
    command: "/opt/splunk/bin/splunk edit cluster-config -mode searchhead -manager_uri https://{{ cluster_manager }}.aws.maximumpigs.com:8089 -secret idxcluster1!"

  - name: Add Cluster Manager as Search Peer
    command: "/opt/splunk/bin/splunk add search-server https://{{ cluster_manager }}.aws.maximumpigs.com:8089 -remoteUsername admin -remotePassword Administrator1!"

# TODO - Enable distributed monitoring

# TODO - Set server roles

  - name: Start Splunk
    command: "/opt/splunk/bin/splunk start"