---
- name: Configure Search Head
  hosts: searchhead
  become: true
  remote_user: ubuntu

  tasks:

  - name: Get hostname
    command: hostname
    register: hostname

  - name: Join the indexer cluster
    command: "/opt/splunk/bin/splunk edit cluster-config -mode searchhead -manager_uri https://splunkmgr0.aws.maximumpigs.com:8089 -secret idxcluster1 -auth admin:Administrator1!"

  - name: Initialise the SH Cluster
    command: "/opt/splunk/bin/splunk init shcluster-config -mgmt_uri https://{{ hostname.stdout }}.aws.maximumpigs.com:8089 -replication_port 9200 -replication_factor 2 -conf_deploy_fetch_url https://splunkmgr0.aws.maximumpigs.com:8089 -secret shcluster1 -shcluster_label shcluster1 -auth admin:Administrator1!"

  - name: Restart Splunk
    command: "/opt/splunk/bin/splunk restart"

  - name: Set the SH Captain on SH0
    command: "/opt/splunk/bin/splunk bootstrap shcluster-captain -servers_list \"https://splunksh0.aws.maximumpigs.com:8089\" -auth admin:Administrator1!"
    when: hostname.stdout == "splunksh0"

  - name: Restart Splunk
    command: "/opt/splunk/bin/splunk restart"