---
- name: Configure Search Head
  hosts: searchhead
  remote_user: ubuntu

  tasks:

  - name: Update all packages to their latest version
    ansible.builtin.apt:
      name: "*"
      state: latest