---
- name: Configure Search Head
  hosts: searchhead
  vars:
    license_manager: "splunkmgr1"
    deployment_server: "splunkmgr1"
    cluster_manager: "splunkmgr0"
    deployer: "splunkmgr1"
    sh_captain: "splunksh0"
  become: true
  remote_user: splunk

  tasks:

# General tasks

  - name: Make sure splunk folder is owned by splunk user
    file:
      path: /opt/splunk
      owner: splunk
      recurse: yes

  - name: Populate service facts
    service_facts:

  - name: Check if Splunkd is running
    systemd_service:
      name: Splunkd.service
      state: started
    check_mode: true
    when: ansible_facts['services']['Splunkd.service']['status'] | default('not-found') != 'not-found'
    register: splunkd

  - name: Initialise and set boot start
    command: "/opt/splunk/bin/splunk enable boot-start -systemd-managed 1 -user splunk --accept-license --answer-yes --seed-passwd Administrator1!"
    when: ansible_facts['services']['Splunkd.service']['status'] | default('not-found') == 'not-found'

  - name: Create _webserver app
    blockinfile: 
      path: /opt/splunk/etc/apps/_webserver/default/web.conf
      create: true
      mode: '0655'
      owner: 'splunk'
      prepend_newline: true
      block: |
        [settings]
        enableSplunkWebSSL = true

  - name: Create _index_and_forward app
    blockinfile: 
      path: /opt/splunk/etc/apps/_index_and_forward/default/outputs.conf
      create: true
      mode: '0655'
      owner: 'splunk'
      prepend_newline: true
      block: |
        [indexAndForward]
        index = false

        [tcpout]
        defaultGroup = discovery-group
        indexAndForward = false

        [tcpout:discovery-group]
        indexerDiscovery = idxdiscovery1

        [indexer_discovery:idxdiscovery1]
        manager_uri= https://{{ cluster_manager }}.aws.maximumpigs.com:8089
        pass4SymmKey = idxdiscovery1  

  - name: Create _license App
    blockinfile: 
      path: /opt/splunk/etc/apps/_license/default/server.conf
      create: true
      mode: '0655'
      owner: 'splunk'
      prepend_newline: true
      block: |
        [license]
        manager_uri = https://{{ license_manager }}.aws.maximumpigs.com:8089
    when: license_manager != inventory_hostname_short

# Node specific tasks

  - name: Create _shclustering app
    blockinfile: 
      path: /opt/splunk/etc/apps/_shclustering/default/server.conf
      create: true
      mode: '0655'
      owner: 'splunk'
      prepend_newline: true
      block: |
        [shclustering]
        disabled = 0
        shcluster_label = shcluster1
        mgmt_uri = https://{{ inventory_hostname_short }}.aws.maximumpigs.com:8089
        replication_factor = 2
        conf_deploy_fetch_url = https://{{ deployer }}.aws.maximumpigs.com:8089
        pass4SymmKey = shcluster1

        [replication_port://9200]

  - name: Make sure splunk folder is owned by splunk user
    file:
      path: /opt/splunk
      owner: splunk
      recurse: yes

  - name: Start Splunk
    command: "/opt/splunk/bin/splunk start"
    when: splunkd.changed == true or ansible_facts['services']['Splunkd.service']['status'] | default('not-found') == 'not-found'

  - name: Restart Splunk
    command: "/opt/splunk/bin/splunk restart"
    when: splunkd.changed == false

  - name: Wait for web server to be available
    uri:
      url: "https://localhost:8000"
      follow_redirects: all
      method: GET
      validate_certs: false
    register: _result
    until: _result.status == 200
    retries: 20
    delay: 5

  - name: Set the SH Captain on SH0
    command: "/opt/splunk/bin/splunk bootstrap shcluster-captain -servers_list \"https://splunksh0.aws.maximumpigs.com:8089, https://splunksh1.aws.maximumpigs.com:8089, https://splunksh2.aws.maximumpigs.com:8089\" -auth admin:Administrator1!"
    when: inventory_hostname_short == sh_captain