---
- name: Update web servers
  hosts: searchhead
  remote_user: ubuntu

  tasks:
  - name: Update cache
    ansible.builtin.apt:
      update_cache: yes

  - name: Update all packages to their latest version
    ansible.builtin.apt:
      name: "*"
      state: latest