---
- name: Configure Search Head
  hosts: searchhead
  become: true
  remote_user: ubuntu

  tasks:

  - name: Join the indexer cluster
    command: "/opt/splunk/bin/splunk edit cluster-config -mode searchhead -manager_uri https://splunkmgr0.aws.maximumpigs.com:8089 -secret idxcluster1 -auth admin:Administrator1!"

  - name: Restart Splunk
    command: "/opt/splunk/bin/splunk restart"