---
- name: Configure Cluster Manager
  hosts: splunksh0
  vars:
    license_manager: "splunkmgr1"
    deployment_server: "splunkmgr1"
    cluster_manager: "splunkmgr0"
    deployer: "splunkmgr1"
    sh_captain: "splunksh0"
  become: true
  remote_user: splunk
  
  tasks:
  - name: Create _shclustering app
    blockinfile: 
      path: /opt/splunk/etc/apps/_shclustering/default/server.conf
      create: true
      mode: '0655'
      owner: 'splunk'
      prepend_newline: true
      block: |
        [shclustering]
        disabled = 0
        shcluster_label = shcluster1
        mgmt_uri = https://{{ inventory_hostname_short }}.aws.maximumpigs.com:8089
        replication_factor = 2
        conf_deploy_fetch_url = https://{{ deployer }}.aws.maximumpigs.com:8089
        pass4SymmKey = shcluster1

        [replication_port://9200]